export const PLATFORM_CAPABILITIES = {
  facebook: {
    oauth: true,
    posting: true,
    analytics: true,
    mediaUpload: true,
    communityPosting: false,
    businessSupport: true,
    webhooks: true,
    supportLevel: "full",
    accountTypes: ["profile"],
    badges: ["Posting", "Analytics"],
  },
  instagram: {
    oauth: true,
    posting: true,
    analytics: true,
    mediaUpload: true,
    communityPosting: false,
    businessSupport: true,
    webhooks: true,
    supportLevel: "full",
    accountTypes: ["professional"],
    badges: ["Posting", "Analytics"],
  },
  threads: {
    oauth: true,
    posting: true,
    analytics: true,
    mediaUpload: true,
    communityPosting: false,
    businessSupport: false,
    webhooks: false,
    supportLevel: "full",
    accountTypes: ["profile"],
    badges: ["Posting", "Analytics"],
  },
  linkedin: {
    oauth: true,
    posting: true,
    analytics: true,
    mediaUpload: true,
    communityPosting: false,
    businessSupport: true,
    webhooks: false,
    supportLevel: "full",
    accountTypes: ["profile", "organization"],
    badges: ["Posting", "Analytics"],
  },
  youtube: {
    oauth: true,
    posting: true,
    analytics: true,
    mediaUpload: true,
    communityPosting: false,
    businessSupport: false,
    webhooks: false,
    supportLevel: "full",
    accountTypes: ["channel"],
    badges: ["Posting", "Analytics", "Media Upload"],
  },
  x: {
    oauth: true,
    posting: true,
    analytics: false,
    mediaUpload: true,
    communityPosting: false,
    businessSupport: true,
    webhooks: true,
    supportLevel: "limited",
    accountTypes: ["profile", "brand"],
    badges: ["Posting", "Limited API"],
  },
  reddit: {
    oauth: true,
    posting: true,
    analytics: false,
    mediaUpload: true,
    communityPosting: true,
    businessSupport: false,
    webhooks: false,
    supportLevel: "limited",
    accountTypes: ["profile", "subreddit"],
    badges: ["Posting", "Limited API"],
  },
  pinterest: {
    oauth: true,
    posting: true,
    analytics: true,
    mediaUpload: true,
    communityPosting: false,
    businessSupport: true,
    webhooks: false,
    supportLevel: "full",
    accountTypes: ["profile", "board"],
    badges: ["Posting", "Analytics"],
  },
  telegram: {
    oauth: false,
    posting: true,
    analytics: false,
    mediaUpload: true,
    communityPosting: true,
    businessSupport: false,
    webhooks: false,
    supportLevel: "limited",
    accountTypes: ["bot", "group", "channel"],
    badges: ["Posting", "Limited API"],
  },
  discord: {
    oauth: true,
    posting: true,
    analytics: false,
    mediaUpload: true,
    communityPosting: true,
    businessSupport: false,
    webhooks: true,
    supportLevel: "limited",
    accountTypes: ["profile", "server", "channel", "webhook"],
    badges: ["Posting", "Messaging", "Limited API"],
  },
  googleBusiness: {
    oauth: true,
    posting: true,
    analytics: true,
    mediaUpload: true,
    communityPosting: false,
    businessSupport: true,
    webhooks: false,
    supportLevel: "full",
    accountTypes: ["business", "location"],
    badges: ["Posting", "Analytics"],
  },
};

export function getPlatformCapabilities(platform) {
  return PLATFORM_CAPABILITIES[platform] || null;
}
